apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: gebiii/my-app:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m