apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-test
  template:
    metadata:
      labels:
        app: final-test
    spec:
      containers:
      - name: final-test
        image: gebiii/argocd-app:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m